<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <li><img src="<?php echo $this->getSkinUrl('images/magnimeiosgateway/Logo_Lusopay_256x85px.png') ?>" border="0" /></li>
    <?php if ($this->getMethod()->getMensagem()): ?>
        <?php echo '<li>' . $this->getMethod()->getMensagem() . '</li>'; ?>
	<?php endif; ?>
    </ul>
</fieldset>